<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qzw5P_A' shared service.

return $this->privates['.service_locator.qzw5P_A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'patientRepository' => ['privates', 'App\\Repository\\PatientRepository', 'getPatientRepositoryService.php', true],
], [
    'patientRepository' => 'App\\Repository\\PatientRepository',
]);
