<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PmGJ4Z9' shared service.

return $this->privates['.service_locator.PmGJ4Z9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'responseRepository' => ['privates', 'App\\Repository\\ResponseRepository', 'getResponseRepositoryService.php', true],
], [
    'responseRepository' => 'App\\Repository\\ResponseRepository',
]);
