<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.NjgWSpf' shared service.

return $this->privates['.service_locator.NjgWSpf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'response' => ['privates', '.errored..service_locator.NjgWSpf.App\\Entity\\Response', NULL, 'Cannot autowire service ".service_locator.NjgWSpf": it references class "App\\Entity\\Response" but no such service exists.'],
], [
    'response' => 'App\\Entity\\Response',
]);
