<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ZHE_jkt' shared service.

return $this->privates['.service_locator.ZHE_jkt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cultureRepository' => ['privates', 'App\\Repository\\CultureRepository', 'getCultureRepositoryService.php', true],
], [
    'cultureRepository' => 'App\\Repository\\CultureRepository',
]);
