<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.A1IdBna' shared service.

return $this->privates['.service_locator.A1IdBna'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cultureRepository' => ['privates', 'App\\Repository\\CultureRepository', 'getCultureRepositoryService.php', true],
    'question' => ['privates', '.errored..service_locator.A1IdBna.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.A1IdBna": it references class "App\\Entity\\Question" but no such service exists.'],
    'translationRepository' => ['privates', 'App\\Repository\\TranslationRepository', 'getTranslationRepositoryService.php', true],
], [
    'cultureRepository' => 'App\\Repository\\CultureRepository',
    'question' => 'App\\Entity\\Question',
    'translationRepository' => 'App\\Repository\\TranslationRepository',
]);
