<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOj4Rckc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOj4Rckc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOj4Rckc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOj4Rckc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOj4Rckc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Oj4Rckc',
    'container.build_id' => 'df11ac7a',
    'container.build_time' => 1564665787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOj4Rckc');
